### PR TITLE
Hotfix ver 2: Flatten Helpers module

### PR DESCRIPTION
**Pull request by thangngoc89**
I've tested this in my project, should work now

### CODE REVIEW

**Comment by grsabreu** [comment]
thanks man!

**Comment by grsabreu** [comment]
https://github.com/Astrocoders/reform/releases/tag/v4.2.5
Release

**Comment by thangngoc89** [comment]
Thank you man for the fast release :+1:

**Comment by fakenickels** [comment]
@all-contributors please add @thangngoc89 for code

**Pull request merged**
