### PR TITLE
New Feature: Focused fields

### PR DESCRIPTION
**Pull request by happylinks**
After some discussion in #57 I made these changes to be able to store the focused field in Reform.

I introduced setFocusedField, unsetFocusedField and focusedField, these can be used on onFocus, onBlur and while checking if you want to show the error message.

Let me know if this is something that you'd like in reform and if I should change something :)

See example below:

**My usecase, hiding the error messages until the input is not focused anymore:**
```js
(
  {
    form,
    handleChange,
    handleSubmit,
    getErrorForField,
    setFocusedField,
    focusedField,
  },
) =>
    <div className="form-group">
      <label htmlFor="email">
        (ste("Email address"))
      </label>
      <input
        id="email"
        type_="text"
        value=form.values.email
        placeholder="julie@example.com"
        onFocus=(_event => setFocusedField(`email))
        onChange=(
          event =>
            handleChange(`email, inputValue(event))
        )
      />
      (
        switch (focusedField) {
        | Some(field) when field !== `email =>
          <p>
            (
              getErrorForField(`email)
              |> Belt.Option.getWithDefault(_, "")
              |> ReasonReact.string
            )
          </p>
        | _ => ReasonReact.null
        }
      )
    </div>
    <div className="form-group">
      <label htmlFor="password">
        (ste("Password"))
      </label>
      <input
        type_="password"
        value=form.values.password
        placeholder="Enter your password"
        onFocus=(
          _event => setFocusedField(`password)
        )
        onChange=(
          event =>
            handleChange(
              `password,
              inputValue(event),
            )
        )
      />
    </div>
    <div className="error-block">
      <p>
        (
          form.error
          |> Belt.Option.getWithDefault(_, "")
          |> ReasonReact.string
        )
      </p>
    </div>
};
```

### CODE REVIEW

**Comment by grsabreu** [comment]
Thank you!

**Comment by grsabreu** [comment]
I'm going to release it tomorrow

**Comment by happylinks** [comment]
Cool! Thanks for the fast response and the library :)

**Comment by grsabreu** [comment]
Released as 5.1.1-beta.6.
Thanks for your contribution

**Pull request merged**
