### PR TITLE
updated deps and PostAddNext.re on packages/demo

### PR DESCRIPTION
**Pull request by idkjs**
Don't know if this is premature...

Updated all the deps in `package.json` and the ReasonApolloHooks code in `demo/PostAddNext.re`

### CODE REVIEW

**Comment by fakenickels** [comment]
hey there, thanks a lot! this is looking good to me, will check it in runtime asap

**Comment by fakenickels** [comment]
Hey there sorry about the delay to merge this, it's because we had a lot of changes in the meanwhile. If you don't mind in opening it again basing it from a more fresh version of `master` I would appreciate. I'll be closing this one for now

**Comment by idkjs** [comment]
Looks like yours is newer than mine so I wont take any action unless you tell me otherwise. Peace to you.

**Comment by fakenickels** [comment]
Indeed I just did here in the last PR

**Pull request closed without merging**
