### PR TITLE
WIP: Multiple field values support with GADTs

### LINKED ISSUE #23: Support state with different type of data
Example:

```reason
module FormParams = {
  type state = {
    name: string,
    age: int,
  };
  type fields = [ | `name |  `age ];
  let lens = [
    (`name, s => s.name, (s, name) => {...s, name}),
    (
      `age,
      s => s.age,
      (s, age) => {...s, age}
    ),
  ];
};
```

My current work around is make a variant like this: 

```
type formValue = | Int(int) | String(string); 
```

Is this the right approach? Could reform support this use case?

### PR DESCRIPTION
**Pull request by grsabreu**
## Proposal: GADTs implementation of ReForm to provide multiple field values support

I have been cracking my head for a really long time on how to do this.
Thankfully to @alexfedoseev discussions in https://discuss.ocaml.org/t/packing-gadt-constructors-in-iterable-data-structure/2678 I finally clicked about it

Closes #23 #52 #52 

Todo

- [x] GADTs support
- [x] Validators GADT concept
- [ ] Nested forms/Field arrays
- [x] More field states (blur, focus)
- [ ] Provide record API interface instead of sending whole self

Usage now

```reason
module FormConfig = {
  type field(_) =
    | Email: field(string)
    | Age: field(int);
  type state = {
    email: string,
    age: int,
  };

  let get: type value. (state, field(value)) => value =
    (state, field) =>
      switch (field) {
      | Email => state.email
      | Age => state.age
      };

  let set: type value. (state, field(value), value) => state =
    (state, field, value) =>
      switch (field) {
      | Email => {...state, email: value}
      | Age => {...state, age: value}
      };
};

module SignUpForm = ReFormNext.Make(FormConfig);

let component = ReasonReact.statelessComponent("SignUp");

let make = _children => {
  ...component,
  render: _self => {
    let getValue = event => ReactEvent.Form.target(event)##value;
    <SignUpForm
      initialState={email: "", age: 0}
      schema={SignUpForm.Validation.Schema([|Email(Email), Min(Age, 18)|])}>
      ...{
           ({ send, state }) =>
             <div>
               <input
                 value={state.values.email}
                 placeholder="Email"
                 onChange={e => send(FieldChangeValue(Email, e->getValue))}
               />
               <input
                 value={string_of_int(state.values.age)}
                 placeholder="Your age"
                 onChange={
                   e =>
                     send(FieldChangeValue(Age, e->getValue->int_of_string))
                 }
               />
             </div>
         }
    </SignUpForm>;
  },
};
```

### CODE REVIEW

**Comment by grsabreu** [comment]
Really want to make lenses a ppx to generate most of the boilerplate

**Comment by grsabreu** [comment]
```reason
module FormConfig = {
  [%lenses]
  type state = {
    email: string,
    age: int,
  };

  module StateLenses = { type field(_); let get; let set; let map; };
};
```

**Comment by guilhermedecampo** [comment]
Just do it 🏎

**Comment by grsabreu** [comment]
https://github.com/Astrocoders/lenses-ppx
lenses are here!
```reason
[%lenses
  type state = {
    email: string,
    age: int,
  }
];

module SignUpForm = ReFormNext.Make(StateLenses);
```

**Comment by guilhermedecampo** [comment]
What's up! This never ends 😂

**Comment by grsabreu** [comment]
@Astrocoders/core I think we are good to merge this as we have a beta, and then we address any other points in other PR, this one is already too bloated

**Comment by medson10** [comment]
gadts + lenses + monorepo structure with demo app 👏 👏 👏 👏 👏 👏 🔝

**Pull request merged**
