### PR TITLE
Hot fix for 4.2.3 breaks semver patch

### PR DESCRIPTION
**Pull request by thangngoc89**
From 4.2.2 to 4.2.3, you have moved modules into individual files which breaks semver and causing namespace conflicting because `Helpers` is such a common module name. This PR made the public API compatible with 4.2.2 and also solve the namespace conflicting issue.

### CODE REVIEW

**Comment by grsabreu** [comment]
Oh god! that's true haha good catch, thanks

**Comment by grsabreu** [comment]
Released!
https://github.com/Astrocoders/reform/releases/tag/v4.2.4

**Comment by thangngoc89** [comment]
@grsabreu I think there are more :cry: . We have Helpers inside Helpers module

**Comment by grsabreu** [comment]
oh jeez 🤔 weird that I thought I had flatten that

**Comment by grsabreu** [comment]
do you wanna send a PR fixing this too?

**Comment by thangngoc89** [comment]
@grsabreu done #36

**Pull request merged**
